openapi: 3.0.3
info:
  title: Smart Contact Manager OpenAPI 3.0
  description: The Project is about creating smart contact manager,Which can be specifically used for business model.This is a web application which can be used as a simple plugin to any existing project.|
   
  termsOfService: http://swagger.io/terms/
  contact:
    email: kondangkelbablu1998@gmail.com
  license:
    name: Smart Contact Manager
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Smart Contact Manager
  url: http://swagger.io
servers:
  - url: http://localhost:8082
  
tags:
  - name: Contact
    description: Apis related to contacts
    externalDocs:
      description: Find out more
      url: http://swagger.io
      
paths:
  /v1/contacts:
    post:
      tags:
        - Contact
      summary: Add a new contat
      description: Add a new contact
      operationId: addContact
      requestBody:
        description: Create a new contact
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
              
      responses:
        '201':
          description: Successful
          content:
            application/json:
              schema:
                type: string
                example:
                  message: "Contact Created Successfully"
                  
        '400':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: string
                example:
                  message: "Invalid Contact Details"
                  
        '500':
            description: Internal Server Error
            content:
              application/json:
                schema:
                  type: string
                  example:
                    message: "Something went Wrong"
        
    delete:
      tags:
        - Contact
      summary: Delete all contacts
      description: Delete all contacts
      operationId: deleteContacts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: string
                example:
                  message: "All Contacts Deleted Successfully"
                  
        '500':
            description: Internal Server Error
            content:
              application/json:
                schema:
                  type: string
                  example:
                    message: "Something went Wrong"
                    
    get:
     
      tags:
        - Contact
      summary: Get all contacts
      description: Get all contacts
      operationId: Get contacts
      parameters:
        - name: page
          in: query
          description: page value for pagination
          required: false
          schema:
            type: integer
            example: 0
        - name: limit
          in: query
          description: limit of records in one page for pagination
          required: false
          schema:
            type: integer
            example: 3 
        - name: name
          in: query
          description: Name of the contact
          required: false
          schema:
            type: string
            example: Bablu  
        - name: personalEmail
          in: query
          description: Name of the personalEmail
          required: false
          schema:
            type: string
            example: kondangkelbablu1998@gmail.com  
        - name: workEmail
          in: query
          description: Name of the workEmail
          required: false
          schema:
            type: string
            example: bablukondangkel 
              
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/contactList'
                
                example:
                  - contactId: 101
                    fullName: Bablu Kondangkel
                    contactNumber: 8252209996
                    personalEmail: kondangkelbablu1998@gmail.com
                        
                  - contactId: 102
                    fullName: Krishna Kondangkel
                    contactNumber: 9936548166
                    personalEmail: krishnakondangkel24@gmail.com
                        
                  - contactId: 103
                    fullName: Sonalika Kondangkel
                    contactNumber: 9934148990
                    personalEmail: saraswatikumari1249@gmail.com
           
        '400':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: string
                example:
                  message: "Invalid Contact Details"
                  
        '404':
             description: Invalid ID Supplies
             content:
               application/json:
                 schema:
                   type: string
                   example:
                      message: "Contact Not Found"   
                      
        '500':
            description: Internal Server Error
            content:
              application/json:
                 schema:
                   type: string
                   example:
                     message: "Server Error"  
                     
  /v1/contacts/{id}:
    patch:
      tags:
          - Contact
      summary: Update contacts by id
      description: Update details of a contact
      operationId: jshd
      parameters:
        - name: id
          in: path
          description: Update specific contact's details
          required: true
          schema:
            type: integer
            default: 10001
            enum: 
             - 10001
  
      responses:
       '200':
          description: successful
          content:
            application/json:
              schema:
                type: string
                example:
                  message: "Update successfully"
                
       '500':
         description: Internal Server Error
         content:
            application/json:
              schema:
                type: string
                example:
                  message: "Server Error"
                  
    delete:
      tags:
          - Contact
      summary: Delete contacts by id
      description: Delete details of a contact
      operationId: jshd
      parameters:
        - name: id
          in: path
          description: Update specific contact's details
          required: true
          schema:
            type: integer
            default: 10001
            enum: 
             - 10001
            
      responses:
       '200':
          description: successful
          content:
            application/json:
              schema:
                type: string
                example:
                  message: "Contact Delete successfully"

       '404':
          description: Contact not found
          content:
            application/json:
              schema:
                type: string
                example:
                  message: Contact not found
          
       '500':
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
                example:
                  message: "Internal Server Error"
    
    get:
      tags:
        - Contact
      summary: Get detils by contactId
      description: Get details of specific contact
      operationId: detailsOfcontact
      parameters:
        - name: id
          in: path
          description: page value for contact
          required: true
          schema:
            type: integer
            example: 1001
            
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
                  
        '400':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: string
                example:
                  message: Invalid ContactId
                  
        '404':
             description: NOT FOUND
             content:
               application/json:
                 schema:
                   type: string
                   example:
                      message: Contact Not Found with ContactId     
                      
        '500':
            description: Internal Server Error
            content:
              application/json:
                 schema:
                   type: string
                   example:
                     message: Server Error   
                     
components:
  schemas:
    contactList:
      type: object
      properties:
        ContactId:
          type: integer
        fullName:
          type: string
        contactNumber:
           type: integer
        personalEmail:
           type: string
    Contact:
      type: object
      properties:
        firstName:
          type: string
          example: "Bablu"
        middleName:   
         type: string
         example: "NA"
        lastName:
          type: string
          example: "Kondangkel"
        contactNumber:  
          type: integer
          example: 8252209996
        personalEmail:
          type: string
          example: "kondangkelbablu1998@gmail.com"
        workingEmail:
          type: string
          example: "bablukondangkel07@gmail.com"
        homeAddress:
          type: string
          example: "Jamshedpur"
        workAddress:
          type: string
          example: "Bangalore"
        departMent:
          type: string
          example: "Software Engeenier"
        website:
          type: string
          example: "http//lindin.com"
  