version: '3.8'

services:
  scm:
    image: 'smartcontactmanager:v1'
    build:
      context: .
    container_name: scm_local
#    depends_on:
#      - db
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=password
     - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/smart_contact_manager
     - SPRING_DATASOURCE_USERNAME=postgres
     - SPRING_DATASOURCE_PASSWORD=password
     - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

    ports:
      - "6868:8080"

#  db:
#    image: postgres
#    container_name: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=smart_contact_manager
#    ports:
#      - "5433:5432"